package com.entity;

// Importing JPA annotations for ORM (Object-Relational Mapping)
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity  // Marks this class as a JPA entity, meaning it will be mapped to a table in the database
@Table(name = "student")  // Specifies the name of the table in the database that this entity will be mapped to
public class StudentEntity {

	@Id  // Marks this field as the primary key of the entity
	@GeneratedValue(strategy = GenerationType.IDENTITY)  // Specifies that the primary key will be auto-generated by the database
	int rollNumber;  // Unique identifier for each student, corresponds to the primary key

	// Attributes of the student entity that will be mapped to columns in the "student" table
	String firstName;  
	String lastName;  
	String email;  
	String Gender;  
	String batchName;  
	String courseName;  

	// Default constructor (no-argument constructor)
	// Required by JPA for entity instantiation
	public StudentEntity() {
	}

	// Parameterized constructor
	// Allows creating a new StudentEntity object with specified values for all attributes
	public StudentEntity(int rollNumber, String firstName, String lastName, String email, String Gender, String batchName, String courseName) {
		this.rollNumber = rollNumber;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.Gender = Gender;
		this.batchName = batchName;
		this.courseName = courseName;
	}

	// Getter and Setter methods for each field
	// These methods allow access to and modification of the entity's properties

	public int getRollNumber() {
		return rollNumber;
	}

	public void setRollNumber(int rollNumber) {
		this.rollNumber = rollNumber;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return Gender;
	}

	public void setGender(String gender) {
		this.Gender = gender;
	}

	public String getBatchName() {
		return batchName;
	}

	public void setBatchName(String batchName) {
		this.batchName = batchName;
	}

	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}
	
}
